import { Alert, KeyboardAvoidingView, Platform, ScrollView, StyleSheet, Text, TextInput, TouchableOpacity, View } from 'react-native';
import { useRef, useState } from 'react';
import { router, useLocalSearchParams } from 'expo-router';
import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { useAuthStore } from '../../src/stores/auth-store';
import { api } from '../../src/api/client';
import { Button, Card, borderRadius, colors, spacing, typography } from '@kansride/ui';

export default function VerifyOTPScreen() {
  const { phone } = useLocalSearchParams<{ phone: string }>(); const [otp, setOtp] = useState(['', '', '', '', '', '']); const [loading, setLoading] = useState(false); const setTokens = useAuthStore((s) => s.setTokens); const inputs = useRef<(TextInput | null)[]>([]);
  const handleOtpChange = (text: string, index: number) => { const next = [...otp]; next[index] = text.slice(-1); setOtp(next); if (text && index < 5) inputs.current[index + 1]?.focus(); };
  const handleKeyPress = (key: string, index: number) => { if (key === 'Backspace' && !otp[index] && index > 0) inputs.current[index - 1]?.focus(); };
  const handleVerify = async () => { const code = otp.join(''); if (code.length !== 6) { Alert.alert('Invalid code', 'Please enter the complete 6-digit code'); return; } setLoading(true); try { const response = await api.postNoAuth<{ accessToken: string; refreshToken: string; user: { id: string; phoneNumber: string; role: string; firstName?: string; lastName?: string } }>('/auth/verify-otp', { phoneNumber: phone, code }); await setTokens(response.accessToken, response.refreshToken, response.user); router.replace(response.user.role === 'driver' || response.user.role === 'driver_applicant' ? '/(main)/home' : '/(auth)/register'); } catch (error: any) { Alert.alert('Verification failed', error.message || 'Invalid OTP code'); } finally { setLoading(false); } };
  return <SafeAreaView style={styles.safe}><KeyboardAvoidingView style={styles.flex} behavior={Platform.OS === 'ios' ? 'padding' : 'height'}><ScrollView contentContainerStyle={styles.content} keyboardShouldPersistTaps="handled"><TouchableOpacity onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.textPrimary} /></TouchableOpacity><View style={styles.hero}><View style={styles.icon}><Ionicons name="chatbubble-ellipses-outline" size={28} color={colors.primary} /></View><Text style={styles.title}>Check your messages</Text><Text style={styles.subtitle}>Enter the 6-digit code sent to{`\n`}<Text style={styles.phone}>{phone}</Text></Text></View><Card variant="raised" shadow="lg" padding="lg"><Text style={styles.codeLabel}>SECURE CODE</Text><View style={styles.otpRow}>{otp.map((digit, i) => <TextInput key={i} ref={(ref) => { inputs.current[i] = ref; }} style={[styles.otpBox, digit && styles.otpFilled]} value={digit} onChangeText={(text) => handleOtpChange(text, i)} onKeyPress={({ nativeEvent }) => handleKeyPress(nativeEvent.key, i)} keyboardType="number-pad" maxLength={1} selectTextOnFocus editable={!loading} />)}</View><Button title="Verify and continue" onPress={() => void handleVerify()} loading={loading} disabled={otp.join('').length !== 6} fullWidth size="lg" /></Card><Text style={styles.help}>Never share this security code with a passenger.</Text></ScrollView></KeyboardAvoidingView></SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { flex: 1, backgroundColor: colors.background }, flex: { flex: 1 }, content: { flexGrow: 1, padding: spacing.lg, justifyContent: 'center' }, back: { width: 44, height: 44, borderRadius: borderRadius.full, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md }, hero: { alignItems: 'center', marginBottom: spacing.lg }, icon: { width: 60, height: 60, borderRadius: borderRadius.xl, backgroundColor: colors.primarySoft, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md }, title: { ...typography.h1, color: colors.textPrimary, textAlign: 'center' }, subtitle: { ...typography.body, color: colors.textSecondary, textAlign: 'center', marginTop: 7 }, phone: { color: colors.textPrimary, fontWeight: '700' }, codeLabel: { ...typography.label, color: colors.textSecondary, textAlign: 'center', marginBottom: spacing.md }, otpRow: { flexDirection: 'row', justifyContent: 'center', gap: 6, marginBottom: spacing.lg }, otpBox: { width: 44, height: 56, borderRadius: borderRadius.lg, borderWidth: 1.5, borderColor: colors.border, backgroundColor: colors.surface, textAlign: 'center', fontSize: 24, fontWeight: '700', color: colors.textPrimary }, otpFilled: { borderColor: colors.primary, backgroundColor: colors.primarySoft }, help: { ...typography.caption, color: colors.textSecondary, textAlign: 'center', marginTop: spacing.lg } });
