import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, ScrollView, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router, useLocalSearchParams } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../../../src/api/client';
import { driverLocationFallback, formatDriverFare, type DriverHistoryRecord } from '../../../src/driver-history';
import { developmentReviewModeEnabled } from '@kansride/config/mobile-runtime';
import { Button, StatusBadge, borderRadius, colors, spacing, typography } from '@kansride/ui';
import { useDriverInsets } from '../../../src/ui/use-driver-insets';

const reviewMode = developmentReviewModeEnabled(process.env.NODE_ENV, process.env.EXPO_PUBLIC_UI_REVIEW_MODE);

export default function DriverRideDetailScreen() {
  const insets = useDriverInsets();
  const { id } = useLocalSearchParams<{ id: string }>();
  const [ride, setRide] = useState<DriverHistoryRecord | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { if (!id) return; setLoading(true); try { setRide(reviewMode ? { id: String(id), status: 'completed', pickupAddress: 'Market Circle', dropoffAddress: 'Airport Roundabout', farePesewas: 2450, createdAt: '2026-08-18T10:00:00Z', completedAt: '2026-08-18T10:24:00Z' } : await api.get<DriverHistoryRecord>(`/rides/${id}`)); setError(null); } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'Ride details unavailable.'); } finally { setLoading(false); } }, [id]);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={[styles.container, styles.center, { paddingTop: insets.top, paddingBottom: insets.bottom }]}><ActivityIndicator color={colors.primary} /></View>;
  if (error || !ride) return <View style={[styles.container, styles.center, { paddingTop: insets.top, paddingBottom: insets.bottom }]}><Ionicons name="alert-circle-outline" size={32} color={colors.error} /><Text style={styles.error}>{error || 'Ride details unavailable.'}</Text><Button title="Retry" onPress={() => void load()} /></View>;
  return <ScrollView style={styles.container} contentContainerStyle={[styles.content, { paddingTop: insets.top, paddingBottom: insets.bottom }]}><TouchableOpacity onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.textPrimary} /></TouchableOpacity><Text style={styles.eyebrow}>TRIP SUMMARY</Text><View style={styles.titleRow}><Text style={styles.title}>Ride details</Text><StatusBadge label={ride.status.replace(/_/g, ' ')} tone={ride.status === 'completed' ? 'success' : 'neutral'} dot /></View><View style={styles.routeCard}><View style={styles.routeRow}><View style={styles.pickupDot} /><View><Text style={styles.label}>PICKUP</Text><Text style={styles.value}>{driverLocationFallback(ride.pickupAddress, ride.pickupLatitude, ride.pickupLongitude)}</Text></View></View><View style={styles.routeLine} /><View style={styles.routeRow}><View style={styles.dropoffDot} /><View><Text style={styles.label}>DESTINATION</Text><Text style={styles.value}>{driverLocationFallback(ride.dropoffAddress, ride.dropoffLatitude, ride.dropoffLongitude)}</Text></View></View></View><View style={styles.fareCard}><Text style={styles.label}>FINAL DRIVER FARE</Text><Text style={styles.fare}>{formatDriverFare(ride.farePesewas)}</Text></View><View style={styles.detailCard}><View style={styles.detailRow}><Text style={styles.detailLabel}>Requested</Text><Text style={styles.detailValue}>{ride.createdAt ? new Date(ride.createdAt).toLocaleString('en-GH') : '--'}</Text></View><View style={styles.divider} /><View style={styles.detailRow}><Text style={styles.detailLabel}>Completed</Text><Text style={styles.detailValue}>{ride.completedAt ? new Date(ride.completedAt).toLocaleString('en-GH') : '--'}</Text></View>{ride.cancellationReason && <><View style={styles.divider} /><View style={styles.detailRow}><Text style={styles.detailLabel}>Cancellation</Text><Text style={styles.detailValue}>{ride.cancellationReason}</Text></View></>}</View></ScrollView>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background }, content: { paddingHorizontal: spacing.lg, gap: 12 }, center: { alignItems: 'center', justifyContent: 'center', paddingHorizontal: spacing.lg }, back: { width: 44, height: 44, borderRadius: borderRadius.full, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.sm }, eyebrow: { ...typography.label, color: colors.primary, letterSpacing: 1.2 }, titleRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: spacing.sm }, title: { ...typography.h1, color: colors.textPrimary }, routeCard: { backgroundColor: colors.surface, borderRadius: borderRadius.xl, padding: spacing.md, borderWidth: 1, borderColor: colors.border }, routeRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 }, pickupDot: { width: 10, height: 10, borderRadius: 5, backgroundColor: colors.pickupPin, marginTop: 5 }, dropoffDot: { width: 10, height: 10, borderRadius: 2, backgroundColor: colors.dropoffPin, marginTop: 5 }, routeLine: { width: 2, height: 28, backgroundColor: colors.borderStrong, marginLeft: 4, marginVertical: 4 }, label: { ...typography.caption, color: colors.textSecondary }, value: { ...typography.bodyBold, color: colors.textPrimary, marginTop: 2 }, fareCard: { backgroundColor: colors.primary, borderRadius: borderRadius.xl, padding: spacing.lg }, fare: { ...typography.h1, color: colors.textInverse, marginTop: 4 }, detailCard: { backgroundColor: colors.surface, borderRadius: borderRadius.xl, padding: spacing.md, borderWidth: 1, borderColor: colors.border }, detailRow: { gap: 3 }, detailLabel: { ...typography.caption, color: colors.textSecondary }, detailValue: { ...typography.small, color: colors.textPrimary, fontWeight: '600' }, divider: { height: 1, backgroundColor: colors.border, marginVertical: 12 }, error: { ...typography.small, color: colors.error, textAlign: 'center', marginVertical: spacing.md } });
