import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../../src/api/client';
import { driverLocationFallback, formatDriverFare, type DriverHistoryRecord } from '../../src/driver-history';
import { developmentReviewModeEnabled } from '@kansride/config/mobile-runtime';
import { Button, StatusBadge, borderRadius, colors, shadows, spacing, typography } from '@kansride/ui';
import { useDriverInsets } from '../../src/ui/use-driver-insets';

const reviewMode = developmentReviewModeEnabled(process.env.NODE_ENV, process.env.EXPO_PUBLIC_UI_REVIEW_MODE);
const REVIEW_RIDES: DriverHistoryRecord[] = [
  { id: 'driver-review-1', status: 'completed', pickupAddress: 'Market Circle', dropoffAddress: 'Airport Roundabout', farePesewas: 2450, createdAt: '2026-08-18T10:00:00Z', completedAt: '2026-08-18T10:24:00Z' },
  { id: 'driver-review-2', status: 'completed', pickupAddress: 'Sekondi Station', dropoffAddress: 'Harbour Area', farePesewas: 1800, createdAt: '2026-08-17T16:00:00Z', completedAt: '2026-08-17T16:18:00Z' },
];

export default function DriverHistoryScreen() {
  const insets = useDriverInsets();
  const [rides, setRides] = useState<DriverHistoryRecord[]>([]);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); try { setRides(reviewMode ? REVIEW_RIDES : await api.get<DriverHistoryRecord[]>('/rides/my-rides')); } catch { setRides([]); setError('Could not load ride history.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={[styles.container, styles.center, { paddingTop: insets.top, paddingBottom: insets.bottom }]}><ActivityIndicator color={colors.primary} /></View>;
  return <View style={[styles.container, { paddingTop: insets.top }]}><View style={styles.header}><TouchableOpacity onPress={() => router.back()} style={styles.back}><Ionicons name="arrow-back" size={20} color={colors.textPrimary} /></TouchableOpacity><Text style={styles.eyebrow}>COMPLETED WORK</Text><Text style={styles.title}>Ride history</Text></View><FlatList data={rides} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} colors={[colors.primary]} />} renderItem={({ item }) => <TouchableOpacity style={styles.card} onPress={() => router.push({ pathname: '/(main)/ride-detail/[id]', params: { id: item.id } })} accessibilityRole="button"><View style={styles.cardTop}><Text style={styles.date}>{item.createdAt ? new Date(item.createdAt).toLocaleDateString('en-GH', { day: 'numeric', month: 'short' }) : 'Recent ride'}</Text><StatusBadge label={item.status.replace(/_/g, ' ')} tone={item.status === 'completed' ? 'success' : 'neutral'} dot /></View><View style={styles.route}><View style={styles.routeRail}><View style={styles.pickupDot} /><View style={styles.line} /><View style={styles.dropoffDot} /></View><View style={styles.routeCopy}><Text style={styles.address}>{driverLocationFallback(item.pickupAddress, item.pickupLatitude, item.pickupLongitude)}</Text><Text style={styles.addressSecondary}>{driverLocationFallback(item.dropoffAddress, item.dropoffLatitude, item.dropoffLongitude)}</Text></View></View><View style={styles.fareRow}><Text style={styles.fareLabel}>Driver fare</Text><Text style={styles.fare}>{formatDriverFare(item.farePesewas)}</Text><Ionicons name="chevron-forward" size={18} color={colors.textMuted} /></View></TouchableOpacity>} ListEmptyComponent={error ? <View style={styles.empty}><Ionicons name="cloud-offline-outline" size={30} color={colors.error} /><Text style={styles.error}>{error}</Text><Button title="Retry" onPress={() => void load()} size="sm" /></View> : <View style={styles.empty}><Ionicons name="map-outline" size={30} color={colors.primary} /><Text style={styles.emptyText}>Completed rides will appear here.</Text></View>} contentContainerStyle={[styles.list, rides.length === 0 && styles.fill, { paddingBottom: insets.bottom }]} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: colors.background, paddingHorizontal: spacing.lg }, fill: { flexGrow: 1 }, center: { alignItems: 'center', justifyContent: 'center' }, header: { marginBottom: spacing.md }, back: { width: 44, height: 44, borderRadius: borderRadius.full, backgroundColor: colors.surface, alignItems: 'center', justifyContent: 'center', marginBottom: spacing.md }, eyebrow: { ...typography.label, color: colors.primary, letterSpacing: 1.2 }, title: { ...typography.h1, color: colors.textPrimary }, list: { gap: 12 }, card: { backgroundColor: colors.surface, borderRadius: borderRadius.xl, padding: spacing.md, borderWidth: 1, borderColor: colors.border, ...shadows.sm }, cardTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, date: { ...typography.label, color: colors.textSecondary }, route: { flexDirection: 'row', marginTop: spacing.md }, routeRail: { width: 18, alignItems: 'center', paddingVertical: 4 }, pickupDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.pickupPin }, line: { width: 2, height: 24, backgroundColor: colors.borderStrong, marginVertical: 3 }, dropoffDot: { width: 8, height: 8, borderRadius: 2, backgroundColor: colors.dropoffPin }, routeCopy: { flex: 1, gap: 13, paddingLeft: 7 }, address: { ...typography.small, color: colors.textPrimary, fontWeight: '700' }, addressSecondary: { ...typography.small, color: colors.textSecondary }, fareRow: { borderTopWidth: 1, borderTopColor: colors.border, marginTop: spacing.md, paddingTop: 12, flexDirection: 'row', alignItems: 'center', gap: 8 }, fareLabel: { ...typography.caption, color: colors.textSecondary, flex: 1 }, fare: { ...typography.bodyBold, color: colors.primary }, empty: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: 12 }, emptyText: { ...typography.small, color: colors.textSecondary }, error: { ...typography.small, color: colors.error, textAlign: 'center' } });
