import { useCallback, useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, RefreshControl, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { router } from 'expo-router';
import { api } from '../../src/api/client';
import { driverLocationFallback, formatDriverFare, type DriverHistoryRecord } from '../../src/driver-history';

export default function DriverHistoryScreen() {
  const [rides, setRides] = useState<DriverHistoryRecord[]>([]);
  const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState<string | null>(null);
  const load = useCallback(async () => { setError(null); try { setRides(await api.get<DriverHistoryRecord[]>('/rides/my-rides')); } catch { setRides([]); setError('Could not load ride history.'); } finally { setLoading(false); setRefreshing(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  if (loading) return <View style={[styles.container, styles.center]}><ActivityIndicator color="#1B8B4B" /></View>;
  return <View style={styles.container}><View style={styles.header}><TouchableOpacity onPress={() => router.back()}><Text style={styles.back}>Back</Text></TouchableOpacity><Text style={styles.title}>Ride history</Text></View><FlatList data={rides} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => { setRefreshing(true); void load(); }} />} renderItem={({ item }) => <TouchableOpacity style={styles.card} onPress={() => router.push({ pathname: '/(main)/ride-detail/[id]', params: { id: item.id } })} accessibilityRole="button"><Text style={styles.status}>{item.status.replace(/_/g, ' ')}</Text><Text>{driverLocationFallback(item.pickupAddress, item.pickupLatitude, item.pickupLongitude)} → {driverLocationFallback(item.dropoffAddress, item.dropoffLatitude, item.dropoffLongitude)}</Text><Text style={styles.fare}>{formatDriverFare(item.farePesewas)}</Text></TouchableOpacity>} ListEmptyComponent={error ? <View style={styles.center}><Text style={styles.error}>{error}</Text><TouchableOpacity onPress={load} style={styles.button}><Text style={styles.buttonText}>Retry</Text></TouchableOpacity></View> : <View style={styles.center}><Text style={styles.empty}>No rides yet.</Text></View>} contentContainerStyle={rides.length === 0 ? styles.fill : undefined} /></View>;
}
const styles = StyleSheet.create({ container: { flex: 1, backgroundColor: '#F8FAFB', padding: 24, paddingTop: 60 }, fill: { flex: 1 }, center: { alignItems: 'center', justifyContent: 'center', padding: 24 }, header: { gap: 8, marginBottom: 16 }, back: { color: '#1B8B4B', fontWeight: '700' }, title: { fontSize: 26, fontWeight: '700', color: '#1A1A2E' }, card: { backgroundColor: '#FFF', padding: 16, borderRadius: 12, borderWidth: 1, borderColor: '#E2E8F0', gap: 6, marginBottom: 10 }, status: { color: '#1B8B4B', fontWeight: '700', textTransform: 'capitalize' }, fare: { color: '#1B8B4B', fontWeight: '700' }, empty: { color: '#64748B' }, error: { color: '#B91C1C', marginBottom: 12 }, button: { backgroundColor: '#1B8B4B', padding: 12, borderRadius: 8 }, buttonText: { color: '#FFF', fontWeight: '700' } });
